# Generated by Django 4.2.24 on 2025-09-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle',
            name='fabricante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
